name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: print job details
        run: |
          echo "github_ref ${{ github.ref }}"
          echo "github_event_name ${{ github.event_name }}"

      - name: npm install
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn install --frozen-lockfile

      - name: lint
        run: yarn lint

      - name: jest test
        run: yarn test

  snapshot-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: run snapshot tests
        run: |
          ./scripts/docker/prepare.sh
          ./scripts/docker/run-tests.sh

      - name: save snapshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: bitmaps_reference
          path: backstop_data/bitmaps_reference

  deploy:
    runs-on: ubuntu-latest
    needs: [test, snapshot-test]
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: generate hash
        run: |
          echo "::set-output name=HASH::123455"
          echo "::set-output name=ZIP_FILE_NAME::storybook---$HASH"

      - name: build docker image
        run: |
          zipFileName = ${{ steps.generate-hash.outputs.ZIP_FILE_NAME }}
          /bin/bash ./scripts/docker/export-prod.sh $zipFileName

      - name: deploy
        run: |
          zipFileName = ${{ steps.generate-hash.outputs.ZIP_FILE_NAME }}
          zip -r $zipFileName docker-image.tar meta.json
          echo "${{ secrets.EC2_RSA }}" > ./identityFile.txt
          chmod 400 ./identityFile.txt
          scp -o "StrictHostKeyChecking=no" -i ./identityFile.txt -r ./$zipFileName.zip ubuntu@ec2-13-40-134-151.eu-west-2.compute.amazonaws.com:/home/ubuntu/departure-lounge/
